# Generated by Django 4.1.6 on 2023-03-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callout", "0008_alter_battle_start_time_and_more"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="invitations",
            field=models.ManyToManyField(null=True, to="callout.battleinvitation"),
        ),
    ]
