# Generated by Django 4.1.6 on 2023-02-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="user_type",
            field=models.CharField(
                choices=[("spectator", "spectator"), ("performer", "performer")],
                max_length=35,
                null=True,
            ),
        ),
    ]
