# Generated by Django 4.1.6 on 2023-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_customer_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="photo",
            field=models.ImageField(null=True, upload_to="static/img/user_photo"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="promo_video",
            field=models.FileField(blank=True, upload_to=None),
        ),
    ]
