# Generated by Django 4.1.6 on 2023-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_customer_photo_alter_customer_promo_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="photo",
            field=models.ImageField(blank=True, upload_to="static/img/user_photo"),
        ),
    ]
