# Generated by Django 4.1.6 on 2023-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_customer_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
