# Generated by Django 4.1.6 on 2023-03-19 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callout", "0017_alter_battle_start_time_and_more"),
        ("account", "0005_alter_customer_changed_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="invitations",
            field=models.ManyToManyField(blank=True, to="callout.battleinvitation"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="subscribtions",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
