# Generated by Django 4.1.6 on 2023-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_customer_city_alter_customer_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="dance_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Popping", "Popping"),
                    ("Hip-hop", "Hip-hop"),
                    ("Experimental", "Experimental"),
                ],
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="nickname",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
