# Generated by Django 4.1.6 on 2023-03-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "callout",
            "0019_battle_track_one_battle_track_three_battle_track_two_and_more",
        ),
        ("account", "0006_alter_customer_invitations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="battles",
            field=models.ManyToManyField(blank=True, to="callout.battle"),
        ),
    ]
