# Generated by Django 4.1.6 on 2023-02-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_customer_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=10),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("spectator", "spectator"), ("performer", "performer")],
                max_length=35,
                null=True,
            ),
        ),
    ]
