# Generated by Django 4.1.6 on 2023-02-21 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_customer_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="subscribtions",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
