# Generated by Django 4.1.6 on 2023-02-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_customer_subscribtions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="promo_video",
            field=models.FileField(blank=True, upload_to="promo_video"),
        ),
    ]
