# Generated by Django 4.1.6 on 2023-02-19 08:50

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(default=datetime.datetime(2023, 2, 19, 10, 50, 0, 922341)),
                ),
                ("rounds_count", models.PositiveIntegerField(default=2)),
                ("music", models.CharField(max_length=255)),
                ("result_score", models.PositiveIntegerField(default=0)),
                (
                    "result_goes_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BattleVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "battle",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="callout.battle"),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BattleInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_and_time",
                    models.DateTimeField(default=datetime.datetime(2023, 2, 19, 10, 50, 0, 922341)),
                ),
                (
                    "music_style",
                    models.CharField(
                        choices=[
                            ("Popping", "Popping"),
                            ("Hip-hop", "Hip-hop"),
                            ("Experimental", "Experimental"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "battle",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="callout.battle"),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
