# Generated by Django 4.1.6 on 2023-03-04 07:45

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callout", "0002_remove_battle_result_goes_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battleinvitation",
            name="battle",
        ),
        migrations.RemoveField(
            model_name="battleinvitation",
            name="performer",
        ),
        migrations.AddField(
            model_name="battle",
            name="invitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="callout.battleinvitation",
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 9, 45, 56, 800083)),
        ),
        migrations.AlterField(
            model_name="battleinvitation",
            name="date_and_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 9, 45, 56, 800083)),
        ),
    ]
