# Generated by Django 4.1.6 on 2023-03-04 08:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callout", "0007_rename_user_battleinvitation_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 10, 8, 24, 268379)),
        ),
        migrations.AlterField(
            model_name="battleinvitation",
            name="date_and_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 10, 8, 24, 268379)),
        ),
    ]
