# Generated by Django 4.1.6 on 2023-03-06 16:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callout", "0008_alter_battle_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleinvitation",
            name="text",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="battle",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 18, 37, 15, 791637)),
        ),
        migrations.AlterField(
            model_name="battleinvitation",
            name="date_and_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 18, 37, 15, 791637)),
        ),
    ]
