# Generated by Django 4.1.6 on 2023-03-07 10:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callout", "0012_alter_battle_start_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="battleinvitation",
            old_name="accepted",
            new_name="accepted_performer",
        ),
        migrations.AddField(
            model_name="battleinvitation",
            name="accepted_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="battle",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 12, 40, 51, 581998)),
        ),
        migrations.AlterField(
            model_name="battleinvitation",
            name="date_and_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 12, 40, 51, 580998)),
        ),
    ]
