# Generated by Django 4.1.6 on 2023-03-23 09:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callout", "0018_alter_battle_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="track_one",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="track_three",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="battle",
            name="track_two",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="battle",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 11, 20, 14, 415685)),
        ),
        migrations.AlterField(
            model_name="battleinvitation",
            name="date_and_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 11, 20, 14, 414685)),
        ),
    ]
